### ISSUE TITLE
Typos in Week 2 Blog

### ISSUE THREAD

**Issue by howtofly-lab** [ossd-s23/Jiajun-Jiao-weekly#1]
Hi, I found some typos in your week 2 blog: "benifit"-> benefit, "establishs" -> establishes, "behavir" -> behavior, "elimitated"-> eliminated, "bulkness" -> bulkiness, "Plege" -> Pledge, "guidlines" -> guidelines, "partiipants" -> participants , "comparision" -> comparison :)

**Comment by Jiajun-Jiao** [comment]
@howtofly-lab Thank you so much for your help! I've fixed all of them.
